# Generated by Django 2.1.5 on 2019-02-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'catalog')},
        ),
        migrations.AlterUniqueTogether(
            name='productentry',
            unique_together={('name', 'category')},
        ),
    ]
