# Generated by Django 2.1.7 on 2019-02-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20190213_1251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productentry',
            unique_together=set(),
        ),
    ]
