# Generated by Django 2.1.7 on 2019-02-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_auto_20190218_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentry',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='productentry',
            name='reference_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='productentry',
            name='sku',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
