# Generated by Django 2.1.7 on 2019-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_auto_20190219_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
