# Generated by Django 2.1.7 on 2019-02-19 11:14

import catalogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_auto_20190219_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(blank=True, upload_to=catalogs.models.upload_path),
        ),
    ]
