# Generated by Django 2.2 on 1980-01-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_auto_20190612_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='catalogs.Catalog'),
        ),
    ]
