# Generated by Django 2.2 on 2019-06-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_auto_19800104_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionproduct',
            options={'verbose_name': 'Collection Product', 'verbose_name_plural': 'Collection Products'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(related_name='collectionsProduct', through='catalogs.CollectionProduct', to='catalogs.ProductEntry'),
        ),
    ]
