# Generated by Django 2.2 on 2019-06-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_auto_20190624_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionproduct',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionProduct',
        ),
    ]
