# Generated by Django 2.2 on 2019-07-09 10:48

import catalogs.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_auto_20190630_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=catalogs.models.product_photo_upload_path),
        ),
    ]
