# Generated by Django 2.2 on 2019-07-11 09:40

import catalogs.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0013_auto_20190709_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=catalogs.models.category_bg_photo_upload_path),
        ),
        migrations.AddField(
            model_name='collection',
            name='background_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=catalogs.models.collection_bg_photo_upload_path),
        ),
    ]
