# Generated by Django 2.2 on 2019-10-12 19:04

import catalogs.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0015_catalog_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='logo_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=catalogs.models.catalog_logo_upload_path),
        ),
    ]
