# Generated by Django 2.2.9 on 2020-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_catalog_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalogs.collection',),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
